apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: mtp
spec:
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: notification-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: mtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: mtp/notification-service:latest
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: mtp-shared-config
          env:
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mtp-secrets
                  key: SMTP_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mtp-secrets
                  key: SMTP_PASSWORD
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mtp-secrets
                  key: TELEGRAM_BOT_TOKEN
