apiVersion: v1
kind: Service
metadata:
  name: reference-data-service
  namespace: mtp
spec:
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: reference-data-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-data-service
  namespace: mtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reference-data-service
  template:
    metadata:
      labels:
        app: reference-data-service
    spec:
      containers:
        - name: reference-data-service
          image: mtp/reference-data-service:latest
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: mtp-shared-config
          env:
            - name: ALPHAVANTAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: mtp-secrets
                  key: ALPHAVANTAGE_KEY
            - name: FINNHUB_KEY
              valueFrom:
                secretKeyRef:
                  name: mtp-secrets
                  key: FINNHUB_KEY
