apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: mtp
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gateway-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: mtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: mtp/gateway-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mtp-shared-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mtp-secrets
                  key: JWT_SECRET
